#!/bin/sh

""":" # pdfsizeopt: PDF file size optimizer

P="$(readlink "$0" 2>/dev/null)"
test "$P" && test "${P#/}" = "$P" && P="${0%/*}/$P"
test "$P" || P="$0"
Q="${P%/*}/.venv/bin/python"
test -n "$PDFSIZEOPT_PYTHON" && exec "$PDFSIZEOPT_PYTHON" -- "$P" "$@"
test -x "$Q" && exec "$Q" -- "$P" "$@"
exec python3 -- "$P" "$@"; exit 1
"""

import os
import os.path
import sys


script_dir = os.path.dirname(__file__)
try:
  __file__ = os.path.join(script_dir, os.readlink(__file__))
  script_dir = os.path.dirname(__file__)
except (OSError, AttributeError, NotImplementedError):
  pass
if os.path.isfile(os.path.join(
    script_dir, 'lib', 'pdfsizeopt', 'main.py')):
  sys.path[0] = os.path.join(script_dir, 'lib')

from pdfsizeopt import main
sys.exit(main.main(sys.argv, script_dir=script_dir))
